### ISSUE TITLE
Error while linking

### ISSUE THREAD

**Issue by jkbailey** [getsentry/react-native-sentry#107]
Ran into an error while installing sentry in react native, during link stage.

```rnpm-install info Linking react-native-sentry android dependency 
rnpm-install info Android module react-native-sentry has been successfully linked 
rnpm-install info Linking react-native-sentry ios dependency 
rnpm-install info iOS module react-native-sentry has been successfully linked 
/Users/***/node_modules/react-native-sentry/scripts/postlink:17
let cachedDsn = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
/Users/***/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-sentry/scripts/postlink" command
    at ChildProcess.prelink (/Users/***/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by HazAT** [comment]
Can you post your version of node please? 
`node -v`

**Comment by jkbailey** [comment]
`v5.4.0`

**Comment by HazAT** [comment]
Hey, is it possible for you to upgrade node?
Since `let` was introduced I guess in node v6.

**Comment by fatinWasta** [comment]
any updates on this one? Having same issue.

**Comment by HazAT** [comment]
@fatinWasta No, not really beside updating your node version.
