### ISSUE TITLE
way to add extraContext in case of unhandled exception/crash

### ISSUE THREAD

**Issue by vincejah** [getsentry/react-native-sentry#137]
I would like to add some context when a crash occurs. I understand that context can be added when capturing exception, but this is only for exceptions that are expected.

Is there a way to do that?

Thanks

**Comment by HazAT** [comment]
Sadly there is nothing like a `onCrashHandler`, what you could do is call`Sentry.setExtraContext` this will always add the context.

**Comment by vincejah** [comment]
Calling `Sentry.setExtraContext` will add the context at a certain moment of time, right?

In my case, I would like to pass a part of my redux store. When I call setExtraContext, it will take a snapshot of it at the time `Sentry.setExtraContext` is called, not at the time of the crash.

Am I wrong?

**Comment by HazAT** [comment]
No that's correct, this is how it works.
You could also try it with `setDataCallback` and filter for the event you want and append data then.

**Comment by grigored** [comment]
Have you looked at [](https://github.com/captbaritone/raven-for-redux) ? I'm using it and it works like a charm. Sends the last state and the last action before the crash.

**Comment by vincejah** [comment]
@grigored How and when do you setup setDataCallback? At your application start? Would you mind providing an example?

**Comment by grigored** [comment]
The documentation on raven-for-redux is pretty good. All you have to do is
```
import Raven from "raven-js";
Raven.config().install();

// where you create the redux store
applyMiddleware(
            createRavenMiddleware(Raven, {
                // Optionally pass some options here.
            }),
            ...//other middleware like thunk, redux-logger etc
        ),
```

**Comment by vincejah** [comment]
@HazAT I am trying to use setDataCallback which seems to be correctly trigger during unhandled crash, but from the logcat, I see the following:
```
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: Error getting Proguard UUIDs.
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: java.io.FileNotFoundException: sentry-debug-meta.properties
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at android.content.res.AssetManager.openAsset(Native Method)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at android.content.res.AssetManager.open(AssetManager.java:359)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at android.content.res.AssetManager.open(AssetManager.java:333)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.android.event.helper.AndroidEventBuilderHelper.getProGuardUuids(AndroidEventBuilderHelper.java:157)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.android.event.helper.AndroidEventBuilderHelper.helpBuildingEvent(AndroidEventBuilderHelper.java:73)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.SentryClient.runBuilderHelpers(SentryClient.java:109)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.SentryClient.sendEvent(SentryClient.java:162)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.Sentry.capture(Sentry.java:160)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at io.sentry.SentryUncaughtExceptionHandler.uncaughtException(SentryUncaughtExceptionHandler.java:48)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at com.google.android.gms.analytics.ExceptionReporter.uncaughtException(Unknown Source)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-12 14:41:42.881 17943 17985 E io.sentry.android.event.helper.AndroidEventBuilderHelper: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
```

How can this file be generated during release build (with assembleRelease)?

**Comment by vincejah** [comment]
I finally finally been able to generate `sentry-debug-meta.properties`by following these guidelines https://github.com/getsentry/sentry-java/blob/master/docs/modules/android.rst.

Unfortunately extraContext is not added. Here is the logcat
```
07-12 15:59:41.932 24597 24632 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"setDataCallBack called","timestamp":1499867981.929} }'
07-12 15:59:41.988 24597 24631 I ReactNativeJS: 'react-native-sentry (setExtraContext):', { myExtraContext: 'yeah',
07-12 15:59:41.993 24597 24632 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"react-native-sentry (setExtraContext): [object Object]","timestamp":1499867981.931} }'
07-12 15:59:46.859 24775 24811 D io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.
07-12 15:59:46.861 24775 24810 I ReactNativeJS: 'react-native-sentry (setDataCallback):', [Function]
07-12 15:59:46.861 24775 24811 D io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='xxx.MainApplication@4d502ac' and dsn='Dsn{uri=https://sentry.io/}'
07-12 15:59:46.919 24775 24811 D io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/com.vtoupet.smartmixin/cache/sentry-buffered-events
07-12 15:59:46.932 24775 24811 I react-native-sentry: startWithDsnString 'https://xxxxxx'
07-12 15:59:46.933 24775 24811 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"react-native-sentry (setDataCallback): function (e) {console.log(\"setDataCallBack called\"),s({myExtraContext:\"yeah\"});}","timestamp":1499867986.858} }'
```

Maybe I am misunderstanding the point of setDataCallBack. I call it right after `Sentry.config(...).install()` and it looks like this
```
Sentry.setDataCallBack(function (data) {
    const reduxStore = store.getState()
    Sentry.setExtraContext({
    app: reduxStore.app,
    auth: reduxStore.auth,
    user: reduxStore.user,
    services: reduxStore.services
  })
})
```

I do not see any added context in the sentry reported issue

**Comment by HazAT** [comment]
@vincejah You should be able to do something like this:
```
Sentry.setDataCallback(function (data) {
  console.log(data.extra);
  data.extra.xxxx = 1;
  return data;
});
```

Be sure to return `data` otherwise, you will not send an event.
`data.extra` contains all the extra properties and you can add more there.

**Comment by vincejah** [comment]
@HazAT Thanks a lot, it works great.
