### ISSUE TITLE
build fails after installing react-native-sentry

### ISSUE THREAD

**Issue by jacquescrocker** [getsentry/react-native-sentry#186]
Seems like an error in the `sentry-cli-binary` dependency

i'm using Node: v6.9.1

```
/Users/jc/Projects/test/node_modules/sentry-cli-binary/index.js:5
let path = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/sentry-cli-binary/bin/sentry-cli:5:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Command /bin/sh failed with exit code 1

```

**Comment by jacquescrocker** [comment]
Same issue with node 8.2.1

**Comment by JAStanton** [comment]
had similar issue, for me it had to do with the fact I was using nvm. I had to modify xcodes build script to make sure I was running nvm. The docs have some details https://docs.sentry.io/clients/react-native/manual-setup/#using-node-with-nvm

**Comment by HazAT** [comment]
@jacquescrocker 
Does the solution that @JAStanton posted, work?

**Comment by HazAT** [comment]
I will close this for now since this should be fixed, feel free to comment again if you are still having trouble with it.
