### ISSUE TITLE
Noisy logs: JNDI not availablejava.lang.ClassNotFoundException: javax.naming.InitialContext

### ISSUE THREAD

**Issue by JAStanton** [getsentry/react-native-sentry#191]
_Platform:_
- [ ]  iOS
- [x]  Android

paranoid redacted `npm ls`:
```
@REDACTED@0.0.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.3
├── react-native@0.44.3
├── react-native-code-push@2.1.1-beta
├── react-native-sentry@0.17.0
```

Config:

```
Sentry.config(__CONFIG__.sentry.dsn, {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  ignoreModulesExclude: [], 
  ignoreModulesInclude: ["RNSentry"], 
}).install();
```

---
I have following issue:

I am getting spammed when booting the app as sentry tries to find all of my configs:

```
08-10 15:58:14.557  2964  3034 D ReactNativeJS: [native] io.sentry.config.Lookup: [io.sentry.config.Lookup lookup] JNDI not availablejava.lang.ClassNotFoundException: javax.naming.InitialContext
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.Class.classForName(Native Method) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.Class.forName(Class.java:324) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.config.Lookup.lookup(Lookup.java:105) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.DefaultSentryClientFactory.getServerName(DefaultSentryClientFactory.java:728) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.DefaultSentryClientFactory.configureSentryClient(DefaultSentryClientFactory.java:272) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.DefaultSentryClientFactory.createSentryClient(DefaultSentryClientFactory.java:246) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.android.AndroidSentryClientFactory.createSentryClient(AndroidSentryClientFactory.java:75) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:64) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.Sentry.init(Sentry.java:81) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at io.sentry.RNSentryModule.startWithDsnString(RNSentryModule.java:98) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.naming.InitialContext" on path: DexPathList[[zip file "/data/app/com.convoy.driver.development-1/base.apk"],nativeLibraryDirectories=[/data/app/com.convoy.driver.development-1/lib/x86, /data/app/com.convoy.driver.development-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	... 20 common frames omitted
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	Suppressed: java.lang.ClassNotFoundException: javax.naming.InitialContext
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 		at java.lang.Class.classForName(Native Method) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504) ~[na:0.0]
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 		... 21 common frames omitted
08-10 15:58:14.557  2964  3034 D ReactNativeJS: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by bretthoerner** [comment]
This is in `sentry-java`, I can reduce the noise as I don't think logging the exception itself is very useful. In addition, I can have it only log that JNDI is missing once. Another user reported this but said they were going to send a PR, but didn't, so I forgot about it.

I can fix early next week when I'm back.

**Comment by JAStanton** [comment]
@bretthoerner is this an issue with my build? I wasn't sure if this was saying javax was missing, I know it doesn't ship with Android but it appears React-Native uses it. Anything I should be concerned about?

**Comment by bretthoerner** [comment]
No, not an issue with your build. In the Java SDK we check for [JNDI](https://en.wikipedia.org/wiki/Java_Naming_and_Directory_Interface) for configuration, which isn't available on Android. We shouldn't be so noisy (though these should at least only be logged at the trace/debug level).

**Comment by bretthoerner** [comment]
Fixed here: https://github.com/getsentry/sentry-java/commit/8d0c80f0000c9e98aff317907b5640427d25c7c5

I'll make a new release soon.
