### ISSUE TITLE
Crash on startup on Android 4.4

### ISSUE THREAD

**Issue by matt-casey** [getsentry/react-native-sentry#233]
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.4.0
5.3.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
    url: 'main.jsbundle'
}).install()
```

---
I have following issue:

I have Sentry set up on my iOS and Android react native project. It seems to work great, however causes a crash on Android version 4.4. The crash happens immediately on startup, before the JS app loads.

I get the same result even if I remove all of the javascript sentry code - it seems to be an issue on the Java side of things.

This happens whether I am running as a local build or a signed release build.

**Steps to reproduce:**
- Install react-native-sentry
- Run `react-native link`
- Run the app

**Actual result:**
- App crashes
![screenshot_1505485553](https://user-images.githubusercontent.com/4960519/30487151-948e8f38-9a00-11e7-9bac-9733f77b7082.png)

```
09-15 10:25:45.972 29555-29555/minibar.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: minibar.android, PID: 29555
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{minibar.android/minibar.android.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                                     at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:77)
                                                                     at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:326)
                                                                     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:227)
                                                                     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
                                                                     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                                     at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
                                                                     at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
                                                                     at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                     at minibar.android.MainActivity.onCreate(MainActivity.java:36)
                                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                     at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:70)
                                                                     at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:326) 
                                                                     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:227) 
                                                                     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                                     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                                     at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                                     at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                                     at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                                     at minibar.android.MainActivity.onCreate(MainActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.tls.OkHostnameVerifier
                                                                     at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:428)
                                                                     at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:108)
                                                                     at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:187)
                                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                     at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:70) 
                                                                     at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:326) 
                                                                     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:227) 
                                                                     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                                     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                                     at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                                     at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                                     at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                                     at minibar.android.MainActivity.onCreate(MainActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:5231) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
```
**Expected result:**
- App runs

**Comment by HazAT** [comment]
Hey, this crash seems to be unrelated to `Sentry`.
Also `url: 'main.jsbundle'`;
`url` is is no valid configuration parameter it shouldn't harm but it doesn't do anything.

**Comment by Bartlomiejsz** [comment]
@HazAT @matt-casey I have the same issue, and I think it is related to Sentry.
This is the report from Play Store Crash:
![image](https://user-images.githubusercontent.com/9566840/37656825-6cee6e04-2c49-11e8-8558-fa23c62b012c.png)
