### ISSUE TITLE
Error on react-native link ...

### ISSUE THREAD

**Issue by dburgmann** [getsentry/react-native-sentry#68]
I get an error when trying to link the package.
```
TypeError: Cannot read property 'match' of undefined
    at patchAlwaysIncludeSwift (/Users/PATHTOAPP/node_modules/react-native-sentry/scripts/postlink:236:39)
    at pbxProject.<anonymous> (/Users/PATHTOAPP/node_modules/react-native-sentry/scripts/postlink:325:7)
    at emitTwo (events.js:106:13)
    at pbxProject.emit (events.js:194:7)
    at pbxProject.<anonymous> (/Users/PATHTOAPP/node_modules/react-native-sentry/node_modules/xcode/lib/pbxProject.js:31:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
/Users/PATHTOAPP/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        
```

```
Error: Error occured during executing "node node_modules/react-native-sentry/scripts/postlink" command
    at ChildProcess.prelink (/Users/PATHTOAPP/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I am on react-native 0.39.2. Any Ideas what might have caused this / how to solve it?

**Comment by mitsuhiko** [comment]
This is resolved in the latest version.
