### ISSUE TITLE
react-native link react-native-sentry fails in node < 7

### ISSUE THREAD

**Issue by dhruvparmar372** [getsentry/react-native-sentry#76]
When running `react-native link react-native-sentry` fails with following error.
```
/Users/dhruv/code/teamweek/teamweek/node_modules/react-native-sentry/scripts/postlink:283
      let buildScripts = Object.values(
                                ^

TypeError: Object.values is not a function
    at pbxProject.<anonymous> (/Users/dhruv/code/teamweek/teamweek/node_modules/react-native-sentry/scripts/postlink:283:33)
    at emitTwo (events.js:106:13)
    at pbxProject.emit (events.js:191:7)
    at pbxProject.<anonymous> (/Users/dhruv/code/teamweek/teamweek/node_modules/xcode/lib/pbxProject.js:31:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/dhruv/code/teamweek/teamweek/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-sentry/scripts/postlink" command
    at ChildProcess.prelink (/Users/dhruv/code/teamweek/teamweek/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

```
node - 6.6.0
react-native-cli: 2.0.1
react-native: 0.44.0
react-native-sentry: 0.11.1
```

Since `Object.values` is not supported in http://node.green/#ES2017-features-Object-static-methods-Object-values in Node < 7.0.0, either [this part](https://github.com/getsentry/react-native-sentry/blob/93c446fcbd60b24b14eddbb05fbcd244224bb7c0/scripts/postlink#L283) should be migrated to use older javascript API or the docs should mention having `node - 7.0.0` as minimum requirement. 

I'd be happy to put in a PR for the migration if that's the way to go.

**Comment by dhruvparmar372** [comment]
fixed in `0.11.2` 🎉
