### ISSUE TITLE
Unable to resolve module `../src/utils` from `node_modules/react-native-sentry/lib/raven-plugin.js`

### ISSUE THREAD

**Issue by messense** [getsentry/react-native-sentry#94]
```
error: bundling: UnableToResolveError: Unable to resolve module `../src/utils` from `/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native-sentry/lib/raven-plugin.js`: Directory /Users/messense/workspace/bosondata/brm-apps/node_modules/react-native-sentry/src/utils doesn't exist
    at ResolutionRequest._loadAsDir (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:485:13)
    at tryResolveSync (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:335:18)
    at tryResolveSync (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest._resolveFileOrDir (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:333:12)
    at ResolutionRequest._resolveNodeDependency (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:341:19)
    at ResolutionRequest.resolveDependency (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
```

version 0.12.3

**Comment by HazAT** [comment]
Fixed `0.12.4`
