### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by maximmcnair** [getsentry/react-native-sentry#95]
Installing through npm currently fails for me.

```
Projects/app/ios  feature/sentry-js-logging ✔                                                                                                                                                         55m
▶ npm install react-native-sentry --save

> sentry-cli-binary@1.13.2 install /Users/fakeuser/Projects/app/node_modules/sentry-cli-binary
> node ./bin/install-sentry-cli

/Users/fakeuser/Projects/app/node_modules/sentry-cli-binary/bin/install-sentry-cli:20
if platform === 'win32' {
   ^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
BoilerRoom@0.0.1 /Users/fakeuser/Projects/app
└── UNMET PEER DEPENDENCY react@16.0.0-alpha.6

npm WARN react-apollo@1.1.0 requires a peer of react@0.14.x || 15.* || ^15.0.0 but none was installed.
npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none was installed.
npm WARN react-native-branch@2.0.0-beta.4 requires a peer of react@>=15.4.0 but none was installed.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-sentry" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sentry-cli-binary@1.13.2 install: `node ./bin/install-sentry-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sentry-cli-binary@1.13.2 install script 'node ./bin/install-sentry-cli'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sentry-cli-binary package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install-sentry-cli
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sentry-cli-binary
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sentry-cli-binary
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fakeuser/.npm/_logs/2017-06-08T14_08_40_345Z-debug.log
```

**Comment by maximmcnair** [comment]
I assume this will be fixed by this PR on `sentry-cli` repo.
https://github.com/getsentry/sentry-cli/pull/79
